# Generated by Django 3.1.7 on 2021-05-27 19:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('availability', models.BooleanField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 19, 30, 13, 671676, tzinfo=utc), verbose_name='last modified')),
                ('validity', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplikacja.directory')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('availability', models.BooleanField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 27, 19, 30, 13, 672139, tzinfo=utc), verbose_name='last modified')),
                ('validity', models.BooleanField(default=True)),
                ('blob', models.FileField(null=True, upload_to='')),
                ('summary', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.directory')),
            ],
        ),
        migrations.CreateModel(
            name='Status_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('line', models.IntegerField(blank=True)),
                ('creation_date', models.DateTimeField(verbose_name='date of creation')),
                ('category', models.CharField(choices=[('proc', 'procedure'), ('prop', 'property'), ('lemm', 'lemma'), ('ass', 'assertion'), ('var', 'Variant'), ('invr', 'Invariant'), ('pre', 'precondition'), ('post', 'Post-condition')], max_length=4)),
                ('status', models.CharField(choices=[('pro', 'Proved'), ('inv', 'Invalid'), ('cex', 'CounterExample'), ('unc', 'Unchecked'), ('val', 'Valid'), ('unk', 'Unknown'), ('tim', 'Timeout')], max_length=3)),
                ('validity', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.file')),
                ('status_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplikacja.status_data')),
            ],
        ),
    ]
